export const ACTIONS = {
  TOGGLE_SHOW_COMPLETED: "TOGGLE_SHOW_COMPLETED",
  SET_LOADING: "SET_LOADING",
  ADD_TODO: "ADD_TODO",
  MARK_TODO_COMPLETED: "MARK_TODO_COMPLETED",
  SET_TODOS: "SET_TODOS",
}
